"""
Clean Test Data Script.
Removes all test cases and dummy data, leaving only genuine present web application data.
"""

import sys
from pathlib import Path
import json

backend_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(backend_dir))

DATA_DIR = backend_dir / "data"


def clean_ideas_json():
    print("\n--- Cleaning data/ideas.json ---")
    ideas_file = DATA_DIR / "ideas.json"
    if not ideas_file.exists():
        print("ideas.json not found.")
        return

    data = json.loads(ideas_file.read_text(encoding="utf-8"))
    original_count = len(data)

    test_titles = [
        "smart attendance system using facial recognition",
        "user a unique ai project",
        "user b blockchain portal",
    ]
    test_ids = {"1", "4", "7", "8", "11", "14"}

    cleaned = {}
    for key, doc in data.items():
        title = (doc.get("title") or "").strip().lower()
        # Keep real user web data
        if str(key) in test_ids or title in test_titles:
            print(f"  [REMOVED TEST IDEA] Key: {key} | Title: '{doc.get('title')}'")
        else:
            cleaned[key] = doc
            print(f"  [KEPT WEB IDEA] Key: {key} | Title: '{doc.get('title')}' | Student: '{doc.get('student_email')}'")

    ideas_file.write_text(json.dumps(cleaned, indent=2, default=str), encoding="utf-8")
    print(f"Cleaned ideas.json: {original_count} -> {len(cleaned)} idea(s) remaining.")


def clean_users_json():
    print("\n--- Cleaning data/users.json ---")
    users_file = DATA_DIR / "users.json"
    if not users_file.exists():
        print("users.json not found.")
        return

    data = json.loads(users_file.read_text(encoding="utf-8"))
    original_count = len(data)

    cleaned = {}
    for email, u in data.items():
        # Remove dummy test accounts generated by tests
        if email.startswith("student_179") or email.startswith("user_") or "@test.edu" in email:
            print(f"  [REMOVED TEST USER] Email: {email}")
        else:
            cleaned[email] = u
            print(f"  [KEPT USER] Email: {email} | Name: '{u.get('name')}' | Role: '{u.get('role')}'")

    # Ensure real web user account exists if they submitted 'flipkart clone'
    govardhan_email = "ngovardhanreddy9381@gmail.com"
    if govardhan_email not in cleaned:
        cleaned[govardhan_email] = {
            "email": govardhan_email,
            "password": "password123",
            "name": "N. Govardhan Reddy",
            "role": "student",
            "rollNo": "21CS9381",
            "branch": "Computer Science & Engineering",
            "year": "4th Year",
            "skills": {"python": 4, "aiml": 4, "react": 3, "fastapi": 4},
            "domains": ["aiml", "web"],
            "hasCompletedProfile": True,
            "createdAt": "2026-09-13T15:30:29Z"
        }
        print(f"  [ENSURED WEB USER] {govardhan_email}")

    users_file.write_text(json.dumps(cleaned, indent=2, default=str), encoding="utf-8")
    print(f"Cleaned users.json: {original_count} -> {len(cleaned)} user(s) remaining.")


def clean_students_json():
    print("\n--- Cleaning data/students.json ---")
    students_file = DATA_DIR / "students.json"
    if not students_file.exists():
        print("students.json not found.")
        return

    data = json.loads(students_file.read_text(encoding="utf-8"))
    original_count = len(data)

    cleaned = {}
    for email, s in data.items():
        if email.startswith("student_179") or email.startswith("user_") or "@test.edu" in email:
            print(f"  [REMOVED TEST STUDENT] Email: {email}")
        else:
            cleaned[email] = s
            print(f"  [KEPT STUDENT] Email: {email}")

    # Add Govardhan student profile
    govardhan_email = "ngovardhanreddy9381@gmail.com"
    if govardhan_email not in cleaned:
        cleaned[govardhan_email] = {
            "first_name": "Govardhan",
            "last_name": "Reddy",
            "name": "Govardhan Reddy",
            "email": govardhan_email,
            "roll_no": "21CS9381",
            "branch": "Computer Science & Engineering",
            "year": "4th Year",
            "role": "student",
            "skills": {"python": 4, "aiml": 4, "react": 3, "fastapi": 4},
            "other_skills": "",
            "domains": ["aiml", "web"],
            "other_domains": "",
            "about_me": "Full stack builder passionate about AI/ML.",
            "team_size": "5",
            "projects": [],
            "student_id": govardhan_email
        }
        print(f"  [ENSURED STUDENT PROFILE] {govardhan_email}")

    students_file.write_text(json.dumps(cleaned, indent=2, default=str), encoding="utf-8")
    print(f"Cleaned students.json: {original_count} -> {len(cleaned)} student(s) remaining.")


def clean_mongodb():
    print("\n--- Cleaning MongoDB Atlas (if reachable) ---")
    try:
        from database import (
            get_database,
            project_ideas_col,
            students_col,
            feasibility_reports_col,
            scope_reports_col,
            tech_stack_reports_col,
            risk_reports_col,
            tracking_reports_col,
            project_milestones_col,
        )
        db = get_database()
        db.command("ping")

        # 1. Delete test project ideas
        test_idea_ids = [1, 4, 7, 8, 11, 14, "1", "4", "7", "8", "11", "14", "std_a_123", "std_b_456"]
        test_titles = [
            "Smart Attendance System using Facial Recognition",
            "User A Unique AI Project",
            "User B Blockchain Portal",
        ]
        q_ideas = {
            "$or": [
                {"id": {"$in": test_idea_ids}},
                {"idea_id": {"$in": test_idea_ids}},
                {"title": {"$in": test_titles}},
                {"student_email": {"$regex": "^student_179"}},
                {"student_email": {"$regex": "^user_.*@test\\.edu"}}
            ]
        }
        res_i = project_ideas_col.delete_many(q_ideas)
        print(f"  [DB] Deleted {res_i.deleted_count} test project idea(s).")

        # 2. Delete test reports & milestones
        p_ids = [1, 4, 7, 8, 11, 14, "1", "4", "7", "8", "11", "14", "std_a_123", "std_b_456"]
        feasibility_reports_col.delete_many({"idea_id": {"$in": p_ids}})
        scope_reports_col.delete_many({"idea_id": {"$in": p_ids}})
        tech_stack_reports_col.delete_many({"idea_id": {"$in": p_ids}})
        risk_reports_col.delete_many({"idea_id": {"$in": p_ids}})
        tracking_reports_col.delete_many({"idea_id": {"$in": p_ids}})
        project_milestones_col.delete_many({"project_id": {"$in": p_ids}})

        # 3. Delete test students
        res_s = students_col.delete_many({
            "$or": [
                {"email": {"$regex": "^student_179"}},
                {"email": {"$regex": "^user_.*@test\\.edu"}}
            ]
        })
        print(f"  [DB] Deleted {res_s.deleted_count} test student(s).")
    except Exception as e:
        print(f"  [DB] MongoDB Atlas cleanup notice (offline/skipped): {e}")


if __name__ == "__main__":
    clean_ideas_json()
    clean_users_json()
    clean_students_json()
    clean_mongodb()
    print("\n--- All test cases data successfully removed. Present web data retained. ---")
