"""
Document Generator Agent (Milestone 3)

On-demand generation of:
- Synopsis (project overview document)
- Methodology Report (technical approach document)
- Progress Report (current status summary)

All generated by Groq LLM with project-specific context and dynamic project-grounded fallbacks.
"""

import json
import os
import re
import datetime
from typing import List, Dict, Any
from dotenv import load_dotenv

load_dotenv()


def _get_groq_models() -> List[str]:
    """Return available Groq models, prioritizing verified working models on this account."""
    chat_model = os.getenv("GROQ_CHAT_MODEL", "qwen/qwen3.8-27b").replace("groq/", "")
    main_model = os.getenv("GROQ_MODEL", "qwen/qwen3.8-27b").replace("groq/", "")
    candidates = [
        chat_model,
        "qwen/qwen3.8-27b",
        "openai/gpt-oss-120b",
        "openai/gpt-oss-20b",
        "allam-2-7b",
    ]
    seen = set()
    return [m for m in candidates if m and not (m in seen or seen.add(m))]


def _parse_json_from_text(text: str) -> dict:
    if not text:
        return {}
    text = str(text).strip()
    try:
        return json.loads(text)
    except Exception:
        pass
    patterns = [
        r"```json\s*\n?(.*?)\n?\s*```",
        r"```\s*\n?(.*?)\n?\s*```",
        r"\{[\s\S]*\}",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, re.DOTALL)
        if match:
            try:
                candidate = match.group(1) if match.lastindex else match.group(0)
                # Remove possible trailing comma before closing brace/bracket
                candidate = re.sub(r",\s*([\]}])", r"\1", candidate)
                return json.loads(candidate)
            except Exception:
                pass
    return {}


def _get_domain_defaults(title: str, domain: str) -> dict:
    """Derive smart domain-specific defaults if user project has minimal specifications."""
    t_lower = title.lower()
    d_lower = domain.lower()

    if any(k in t_lower or k in d_lower for k in ["flipkart", "amazon", "e-commerce", "ecommerce", "shop", "store", "cart"]):
        return {
            "tech_stack": ["React.js", "Node.js", "Express.js", "MongoDB", "Redux Toolkit", "Stripe API", "Tailwind CSS", "JWT"],
            "modules": ["Product Catalog & Search Filter", "Cart & Checkout Management", "Payment Gateway Integration", "Order History & Tracking", "Admin Inventory Dashboard"],
            "phases": [
                {"phase": "Phase 1: Catalog Architecture & Data Modeling", "duration": "Weeks 1-2", "activities": ["Product schema & category taxonomy design", "Database indexing for search filters", "Mock product dataset generation"], "deliverable": "Catalog Specification & Schema Document"},
                {"phase": "Phase 2: Authentication & Cart Engine", "duration": "Weeks 3-4", "activities": ["JWT auth & secure session handling", "Persistent shopping cart state with Redux", "Price & coupon calculation service"], "deliverable": "Cart & User Service Prototype"},
                {"phase": "Phase 3: Checkout & Payment Gateway Pipeline", "duration": "Weeks 5-6", "activities": ["Stripe/Razorpay API integration", "Idempotent payment webhook listeners", "Order confirmation receipt generation"], "deliverable": "End-to-End Payment Flow"},
                {"phase": "Phase 4: Admin Portal & Order Fulfillment", "duration": "Weeks 7-8", "activities": ["Inventory tracking dashboard", "Order status transition workflow", "Customer review and rating module"], "deliverable": "Merchant Management Module"},
                {"phase": "Phase 5: Concurrency Testing & Final Deployment", "duration": "Weeks 9-10", "activities": ["Cart contention & load stress tests", "OWASP security audit for payment endpoints", "Faculty defense documentation"], "deliverable": "Final Capstone Package"}
            ]
        }
    elif any(k in t_lower or k in d_lower for k in ["health", "diet", "calorie", "medical", "hospital", "patient", "aiml", "ai"]):
        return {
            "tech_stack": ["Python", "Flask", "PostgreSQL", "PyTorch / TensorFlow", "React.js", "Docker", "OpenCV"],
            "modules": ["User Health Profile & Daily Metrics", "Meal Logging & Calorie Estimation", "Deep Learning Food Classifier", "Dietary Recommendation Engine", "Progress Tracking Analytics"],
            "phases": [
                {"phase": "Phase 1: Environment & Core Health Data Modeling", "duration": "Weeks 1-2", "activities": ["PostgreSQL schema for user health metrics", "Docker containerization for Flask and DB", "RESTful API endpoints for auth and profiles"], "deliverable": "Architecture Baseline Document"},
                {"phase": "Phase 2: Meal Logging & Nutritional Database", "duration": "Weeks 3-4", "activities": ["Food composition database integration", "Daily macronutrient calculation logic", "Meal entry CRUD API endpoints"], "deliverable": "Nutritional Service Prototype"},
                {"phase": "Phase 3: Computer Vision & Calorie Estimation", "duration": "Weeks 5-6", "activities": ["Food-101 model fine-tuning with MobileNet", "Inference microservice optimization (<200ms)", "Portion volume estimation algorithms"], "deliverable": "ML Inference Module"},
                {"phase": "Phase 4: AI Recommendations & User Dashboard", "duration": "Weeks 7-8", "activities": ["Caloric deficit/surplus advice engine", "Interactive charts with Recharts in React", "Exportable health progress reports"], "deliverable": "Integrated Web Application"},
                {"phase": "Phase 5: Model Benchmarking & Final Validation", "duration": "Weeks 9-10", "activities": ["Classification top-5 accuracy validation", "Pytest suite with 80%+ code coverage", "Comprehensive capstone report"], "deliverable": "Final Defense Package"}
            ]
        }
    else:
        return {
            "tech_stack": ["React.js", "FastAPI", "PostgreSQL", "Docker", "Git", "REST APIs"],
            "modules": [f"{title} Core Workflow", "User Access & Role Management", "Data Processing Engine", "Analytics & Reporting", "System Integration"],
            "phases": [
                {"phase": f"Phase 1: Requirements & Architecture Baseline for {title}", "duration": "Weeks 1-2", "activities": ["Requirements formalization", "System boundary definition", "Database entity relationship design"], "deliverable": "Architecture Specification"},
                {"phase": f"Phase 2: Foundational Services & API Development", "duration": "Weeks 3-4", "activities": ["Authentication and user session services", "Core operational REST endpoints", "Database migration scripts"], "deliverable": "API Service Prototype"},
                {"phase": f"Phase 3: Core Implementation & Domain Logic", "duration": "Weeks 5-6", "activities": [f"Implementation of key {title} modules", "Frontend integration with backend services", "Error handling and edge case validation"], "deliverable": "Working Prototype"},
                {"phase": f"Phase 4: Quality Assurance & Performance Optimization", "duration": "Weeks 7-8", "activities": ["Automated unit and integration testing", "API latency profiling and database indexing", "User acceptance validation"], "deliverable": "Verified System Build"},
                {"phase": f"Phase 5: Documentation & Capstone Evaluation", "duration": "Weeks 9-10", "activities": ["Technical documentation compilation", "User manual and deployment guide", "Viva presentation slide deck"], "deliverable": "Final Project Package"}
            ]
        }


def generate_synopsis(
    idea_data: dict,
    student_info: dict = None,
    scope_report: dict = None,
    tech_stack_report: dict = None,
    full_context: dict = None,
) -> dict:
    """Generate a formal project synopsis document uniquely customized to the project."""
    fc = full_context or {}
    title = idea_data.get("title") or fc.get("title") or "Untitled Project"
    desc = idea_data.get("desc") or fc.get("desc", "")
    domain = idea_data.get("domain") or fc.get("domain", "Computer Science")
    team_size = idea_data.get("teamSize") or idea_data.get("team_size") or fc.get("team_size", "3")
    duration_days = idea_data.get("durationDays") or idea_data.get("duration_days") or fc.get("duration_days", 30)
    student_info = student_info or fc.get("student_info", {})
    scope_report = scope_report or fc.get("scope_report", {})
    tech_stack_report = tech_stack_report or fc.get("tech_stack_report", {})

    domain_defaults = _get_domain_defaults(title, domain)

    problem_statement = fc.get("problem_statement") or (scope_report.get("problemStatement") if scope_report else "")
    objectives = fc.get("objectives") or (scope_report.get("objectives") if scope_report else [])
    tech_stack = fc.get("tech_stack") or (list((tech_stack_report.get("recommended_stack") or {}).keys()) if tech_stack_report else []) or domain_defaults["tech_stack"]
    modules = fc.get("project_modules") or idea_data.get("features", []) or domain_defaults["modules"]

    try:
        from groq import Groq
        api_key = os.getenv("GROQ_API_KEY")
        if api_key:
            client = Groq(api_key=api_key)
            prompt = f"""You are an elite academic project documentation specialist.
Generate a formal, rigorous academic project synopsis uniquely crafted for this specific project.
CRITICAL MANDATE: Base the synopsis ENTIRELY on the specific details of "{title}".
Do NOT use generic placeholder text. Mention the exact technical components, algorithms, databases, and problem constraints of "{title}".

PROJECT DETAILS:
- Title: {title}
- Domain: {domain.upper()}
- Description: {desc}
- Problem Statement: {problem_statement or desc}
- Objectives: {'; '.join(objectives) if objectives else f'Develop and deploy functional {title}'}
- Technology Stack: {', '.join(tech_stack[:8])}
- Core Modules / Features: {', '.join(modules[:6])}
- Team Size: {team_size} members | Duration: {duration_days} days ({round(int(duration_days)/7)} weeks)
- Student Author: {student_info.get('firstName', '')} {student_info.get('lastName', '')} ({student_info.get('branch', 'CSE')})

Return a JSON document with this exact schema:
{{
  "title": "{title}",
  "subtitle": "Academic Project Synopsis",
  "date": "{datetime.datetime.now().strftime('%B %Y')}",
  "sections": {{
    "abstract": "Formal 3-4 sentence academic abstract describing the context of {title}, specific engineering challenges, proposed solution, and tangible deliverables.",
    "problem_statement": "Detailed paragraph explaining the exact academic and practical problems addressed by {title}.",
    "objectives": [
      "Specific technical objective 1 for {title}",
      "Specific technical objective 2 for {title}",
      "Specific technical objective 3 for {title}"
    ],
    "project_scope": "Scope boundaries, target users, and key architectural deliverables for {title}.",
    "modules": [
      "Module 1: detailed technical description",
      "Module 2: detailed technical description",
      "Module 3: detailed technical description"
    ],
    "methodology_overview": "Sprint-based iterative engineering methodology detailing sprint cycles, code reviews, and quality gates for {title}.",
    "expected_outcomes": [
      "Outcome 1: production-grade prototype for {title}",
      "Outcome 2: verified test suite and benchmark metrics",
      "Outcome 3: academic documentation and viva defense deck"
    ],
    "conclusion": "Concluding summary emphasizing the innovation, reliability, and academic rigor of {title}."
  }}
}}
Return ONLY valid JSON. No conversational preamble."""

            for model in _get_groq_models():
                try:
                    resp = client.chat.completions.create(
                        model=model,
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.3,
                        max_tokens=900,
                    )
                    parsed = _parse_json_from_text(resp.choices[0].message.content.strip())
                    if parsed and "sections" in parsed and parsed["sections"].get("abstract"):
                        parsed["ai_generated"] = True
                        parsed["doc_type"] = "synopsis"
                        parsed["generated_at"] = datetime.datetime.utcnow().isoformat()
                        return parsed
                except Exception as e:
                    print(f"[DOC AGENT] Synopsis model {model} attempt failed: {e}")
                    continue
    except Exception as e:
        print(f"[DOC AGENT] Synopsis LLM failed: {e}")

    # Dynamic project-specific fallback
    return {
        "title": title,
        "subtitle": "Academic Project Synopsis",
        "date": datetime.datetime.now().strftime('%B %Y'),
        "doc_type": "synopsis",
        "generated_at": datetime.datetime.utcnow().isoformat(),
        "ai_generated": False,
        "sections": {
            "abstract": (
                f"The '{title}' project presents an engineering solution within the {domain.upper()} domain. "
                f"{desc if desc else f'The system is designed to deliver reliable performance using {tech_stack[0]}.'} "
                f"Developed by a team of {team_size} over a {duration_days}-day timeline, the platform incorporates rigorous architectural design, modular services, and empirical testing."
            ),
            "problem_statement": problem_statement or f"Contemporary systems in {domain.upper()} face challenges regarding usability, modular scalability, and responsive data handling. '{title}' directly addresses these issues with dedicated service components.",
            "objectives": objectives or [
                f"Architect and develop a resilient end-to-end prototype for '{title}' using {tech_stack[0] if tech_stack else 'modern web technologies'}",
                f"Implement core modules ({', '.join(modules[:3])}) within a {duration_days}-day timeframe",
                f"Achieve automated test coverage and compile comprehensive academic project documentation",
            ],
            "project_scope": (
                f"In-scope: Development and validation of core modules ({', '.join(modules[:4])}). "
                f"Tech stack includes {', '.join(tech_stack[:4])}. Out-of-scope: Third-party commercial billing infrastructure and distributed multi-region clustering."
            ),
            "modules": [f"{m}: Core service implementation supporting {title} workflow." for m in modules[:5]],
            "methodology_overview": f"Sprint-based Agile lifecycle consisting of 2-week iterations, continuous integration, milestone reviews, and automated testing.",
            "expected_outcomes": [
                f"A validated functional prototype of '{title}'",
                f"Verified API contracts and automated test suite",
                f"Complete academic documentation and project presentation",
            ],
            "conclusion": f"'{title}' demonstrates a scalable, academically rigorous software engineering solution meeting all faculty capstone requirements.",
        },
    }


def generate_methodology(
    idea_data: dict,
    scope_report: dict = None,
    tech_stack_report: dict = None,
    feasibility_report: dict = None,
    full_context: dict = None,
) -> dict:
    """Generate a formal methodology report with phases and activities tailored 100% to the project."""
    fc = full_context or {}
    title = idea_data.get("title") or fc.get("title") or "Untitled Project"
    domain = idea_data.get("domain") or fc.get("domain", "Computer Science")
    duration_days = idea_data.get("durationDays") or idea_data.get("duration_days") or fc.get("duration_days", 30)
    team_size = idea_data.get("teamSize") or idea_data.get("team_size") or fc.get("team_size", "3")
    desc = idea_data.get("desc") or fc.get("desc", "")

    domain_defaults = _get_domain_defaults(title, domain)

    tech_stack = fc.get("tech_stack") or (list((tech_stack_report.get("recommended_stack") or {}).keys()) if tech_stack_report else []) or domain_defaults["tech_stack"]
    milestones = fc.get("milestones", [])
    risks = fc.get("identified_risks", [])
    mitigations = fc.get("mitigation_actions", [])
    modules = fc.get("project_modules") or idea_data.get("features", []) or domain_defaults["modules"]

    try:
        from groq import Groq
        api_key = os.getenv("GROQ_API_KEY")
        if api_key:
            client = Groq(api_key=api_key)
            prompt = f"""You are a principal software architect and academic guide.
Generate a comprehensive Methodology & Technical Approach document for the project:
PROJECT: {title}
Domain: {domain.upper()}
Duration: {duration_days} days ({round(int(duration_days)/7)} weeks) | Team Size: {team_size} members
Description: {desc}
Technologies: {', '.join(tech_stack[:8])}
Modules: {', '.join(modules[:6])}
Risks & Mitigations: {'; '.join(mitigations[:3]) if mitigations else 'Weekly sprint check-ins'}

CRITICAL INSTRUCTIONS:
1. Every phase MUST be explicitly named after real technical deliverables for "{title}".
2. DO NOT use generic phases like "Phase 1: Requirements & Analysis" or "Phase 3: Core Implementation".
   - If {title} is an e-commerce platform (like flipkart clone), phases must be about Product Catalog, Cart/Checkout, Payment Gateway, Order Fulfillment, etc.
   - If {title} is an AI/Health tracker, phases must be about Food Recognition, Calorie Estimation, Meal Logging, Health Analytics, etc.
3. Every activity in each phase must detail tangible tasks (e.g. database schema, API routes, state management, test suites).

Return JSON with this schema:
{{
  "title": "Methodology: {title}",
  "doc_type": "methodology",
  "development_model": "Agile Iterative Framework (2-Week Sprints)",
  "phases": [
    {{
      "phase": "Phase 1: [Specific Foundation & Architecture for {title}]",
      "duration": "Weeks 1-2",
      "activities": [
        "Concrete technical activity 1 for {title}",
        "Concrete technical activity 2 for {title}",
        "Concrete technical activity 3 for {title}"
      ],
      "deliverable": "Specific architectural deliverable for {title}"
    }},
    {{
      "phase": "Phase 2: [Specific Core Service 1 for {title}]",
      "duration": "Weeks 3-4",
      "activities": [
        "Concrete technical activity 1",
        "Concrete technical activity 2"
      ],
      "deliverable": "Specific working service deliverable"
    }},
    {{
      "phase": "Phase 3: [Specific Core Service 2 for {title}]",
      "duration": "Weeks 5-6",
      "activities": [
        "Concrete technical activity 1",
        "Concrete technical activity 2"
      ],
      "deliverable": "Specific integrated deliverable"
    }},
    {{
      "phase": "Phase 4: [Testing, Security & Integration for {title}]",
      "duration": "Weeks 7-8",
      "activities": [
        "Automated testing suite implementation",
        "Security validation and performance tuning"
      ],
      "deliverable": "Verified release build"
    }},
    {{
      "phase": "Phase 5: [Final Deployment & Academic Defense for {title}]",
      "duration": "Weeks 9-10",
      "activities": [
        "Containerized production deployment",
        "Academic dissertation and viva preparation"
      ],
      "deliverable": "Final Capstone Package"
    }}
  ],
  "tools_and_technologies": {json.dumps(tech_stack[:8])},
  "testing_strategy": "Multi-tier testing: unit testing with Jest/Pytest, API contract tests via Postman/Newman, and end-to-end user scenario validation.",
  "risk_mitigation_approach": "{'; '.join(mitigations[:2]) if mitigations else 'Weekly milestone tracking, blocker escalation, and sprint re-alignment.'}"
}}
Return ONLY valid JSON. No markdown preamble."""

            for model in _get_groq_models():
                try:
                    resp = client.chat.completions.create(
                        model=model,
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.3,
                        max_tokens=950,
                    )
                    parsed = _parse_json_from_text(resp.choices[0].message.content.strip())
                    phases = parsed.get("phases") or parsed.get("Phases") or []
                    if parsed and phases and len(phases) >= 3:
                        parsed["phases"] = phases
                        parsed["ai_generated"] = True
                        parsed["doc_type"] = "methodology"
                        parsed["generated_at"] = datetime.datetime.utcnow().isoformat()
                        return parsed
                    else:
                        print(f"[DOC AGENT] Model {model} response parse note. Parsed keys: {list(parsed.keys()) if parsed else 'None'}. Raw snippet: {resp.choices[0].message.content[:150]}")
                except Exception as e:
                    print(f"[DOC AGENT] Methodology model {model} attempt failed: {e}")
                    continue
    except Exception as e:
        print(f"[DOC AGENT] Methodology LLM failed: {e}")

    # Dynamic fallback based on domain and actual milestones
    phases = []
    if milestones and len(milestones) >= 3:
        weeks_per = max(1, round(int(duration_days) / (len(milestones) * 7)))
        for i, m in enumerate(milestones[:5]):
            m_title = m.get("title", f"Sprint {i+1}")
            m_tasks = m.get("deliverables") or m.get("tasks") or [f"Implement {m_title}", f"Validate {m_title}"]
            phases.append({
                "phase": f"Phase {i+1}: {m_title}",
                "duration": f"Weeks {i*weeks_per + 1}-{(i+1)*weeks_per}",
                "activities": m_tasks[:3],
                "deliverable": m_tasks[0] if m_tasks else f"{m_title} Milestone Deliverable"
            })
    else:
        phases = domain_defaults["phases"]

    return {
        "title": f"Methodology: {title}",
        "doc_type": "methodology",
        "generated_at": datetime.datetime.utcnow().isoformat(),
        "ai_generated": False,
        "development_model": "Agile (Sprint-Based Iterations)",
        "tools_and_technologies": tech_stack,
        "testing_strategy": f"Automated test coverage for {title} components, REST API schema validation, and user integration testing.",
        "risk_mitigation_approach": (
            "; ".join(mitigations[:2]) if mitigations else
            "Weekly check-ins, automated milestone re-alignment for blockers, and incremental feature delivery."
        ),
        "phases": phases,
    }


def generate_progress_report(
    idea_data: dict,
    check_ins: list = None,
    risk_report: dict = None,
    full_context: dict = None,
) -> dict:
    """Generate a formal progress report grounded in real tasks, check-ins, and risks."""
    fc = full_context or {}
    title = idea_data.get("title") or fc.get("title") or "Untitled Project"
    domain = idea_data.get("domain") or fc.get("domain", "Computer Science")
    check_ins = check_ins or fc.get("check_ins", [])
    risk_report = risk_report or fc.get("risk_report", {})
    completed_tasks = fc.get("completed_tasks", [])
    pending_tasks = fc.get("pending_tasks", [])
    identified_risks = fc.get("identified_risks", [])
    mitigations = fc.get("mitigation_actions", [])

    domain_defaults = _get_domain_defaults(title, domain)

    if not completed_tasks and not pending_tasks:
        completed_tasks = [f"Initial architecture for {title}", f"Repository & environment setup"]
        pending_tasks = [f"Core {domain_defaults['modules'][0]} API", f"{domain_defaults['modules'][1]} integration", "Test suite & documentation"]

    current_progress = check_ins[-1].get("progress_pct", fc.get("overall_progress", 0)) if check_ins else fc.get("overall_progress", 35)
    total_weeks = len(check_ins) or 1

    try:
        from groq import Groq
        api_key = os.getenv("GROQ_API_KEY")
        if api_key:
            client = Groq(api_key=api_key)
            prompt = f"""You are an academic project progress evaluator.
Generate a formal, evidence-backed Project Progress Report for:
PROJECT: {title}
Domain: {domain.upper()}
Overall Completion: {current_progress}% across {total_weeks} recorded weekly review(s).
Completed Tasks: {', '.join(completed_tasks[:6])}
Pending Deliverables: {', '.join(pending_tasks[:6])}
Identified Project Risks: {', '.join(identified_risks[:3]) if identified_risks else 'Downstream integration dependencies'}

Generate JSON with:
{{
  "title": "Progress Report: {title}",
  "doc_type": "progress_report",
  "overall_progress": {current_progress},
  "total_check_ins": {total_weeks},
  "status": "{"On Track" if current_progress >= 60 else "At Risk" if current_progress >= 30 else "Behind Schedule"}",
  "executive_summary": "Formal 3-sentence summary analyzing development velocity on {title}, milestone completion, and immediate risk mitigation.",
  "completed_tasks": {json.dumps(completed_tasks[:6])},
  "pending_tasks": {json.dumps(pending_tasks[:6])},
  "top_risks": {json.dumps(identified_risks[:3] if identified_risks else ["Sprint delivery deadline", "Integration testing coverage"])},
  "next_steps": [
    "Prioritize top pending deliverable: {pending_tasks[0] if pending_tasks else 'API services'}",
    "Conduct integration verification tests",
    "Prepare status update for next faculty mentor review"
  ]
}}
Return ONLY valid JSON."""

            for model in _get_groq_models():
                try:
                    resp = client.chat.completions.create(
                        model=model,
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.3,
                        max_tokens=750,
                    )
                    parsed = _parse_json_from_text(resp.choices[0].message.content.strip())
                    if parsed and "overall_progress" in parsed and "executive_summary" in parsed:
                        parsed["ai_generated"] = True
                        parsed["doc_type"] = "progress_report"
                        parsed["generated_at"] = datetime.datetime.utcnow().isoformat()
                        parsed["weekly_progress"] = [
                            {
                                "week": i + 1,
                                "date": str(ci.get("submitted_at", ""))[:10] or f"Week {i+1}",
                                "progress": ci.get("progress_pct", current_progress),
                                "mood": ci.get("mood", "good"),
                                "blockers": ci.get("blockers", "None"),
                                "completed_tasks": ci.get("completed_tasks", completed_tasks[:2]),
                                "pending_tasks": ci.get("pending_tasks", pending_tasks[:2]),
                            }
                            for i, ci in enumerate(check_ins)
                        ] if check_ins else [
                            {
                                "week": 1,
                                "date": datetime.datetime.now().strftime("%Y-%m-%d"),
                                "progress": current_progress,
                                "mood": "good",
                                "blockers": "None",
                                "completed_tasks": completed_tasks[:2],
                                "pending_tasks": pending_tasks[:2],
                            }
                        ]
                        return parsed
                except Exception as e:
                    print(f"[DOC AGENT] Progress report model {model} attempt failed: {e}")
                    continue
    except Exception as e:
        print(f"[DOC AGENT] Progress Report LLM failed: {e}")

    # Fallback
    return {
        "title": f"Progress Report: {title}",
        "doc_type": "progress_report",
        "generated_at": datetime.datetime.utcnow().isoformat(),
        "ai_generated": False,
        "overall_progress": current_progress,
        "total_check_ins": total_weeks,
        "status": "On Track" if current_progress >= 60 else "At Risk" if current_progress >= 30 else "Behind Schedule",
        "executive_summary": (
            f"The '{title}' project has logged {total_weeks} review milestone(s) reaching an estimated {current_progress}% completion. "
            f"Active work has delivered {', '.join(completed_tasks[:2])}. "
            f"{'Sprint velocity is satisfactory.' if current_progress >= 50 else 'Proactive sprint re-alignment is recommended to keep target milestone dates.'}"
        ),
        "weekly_progress": [
            {
                "week": i + 1,
                "date": str(ci.get("submitted_at", ""))[:10] or f"Week {i+1}",
                "progress": ci.get("progress_pct", current_progress),
                "mood": ci.get("mood", "good"),
                "blockers": ci.get("blockers", "None"),
                "completed_tasks": ci.get("completed_tasks", []),
                "pending_tasks": ci.get("pending_tasks", []),
            }
            for i, ci in enumerate(check_ins)
        ] if check_ins else [
            {
                "week": 1,
                "date": datetime.datetime.now().strftime("%Y-%m-%d"),
                "progress": current_progress,
                "mood": "good",
                "blockers": "None",
                "completed_tasks": completed_tasks[:2],
                "pending_tasks": pending_tasks[:2],
            }
        ],
        "completed_tasks": completed_tasks[:6],
        "pending_tasks": pending_tasks[:6],
        "top_risks": identified_risks[:3] if identified_risks else ["Sprint delivery deadline", "Integration testing coverage"],
        "next_steps": [
            f"Execute next sprint deliverable: {pending_tasks[0] if pending_tasks else 'Core API'}",
            "Maintain weekly check-ins to monitor velocity",
            "Prepare code artifacts for faculty milestone evaluation",
        ],
    }
